### ISSUE TITLE
Wektor przerwań

### ISSUE THREAD

**Issue by tomekjaworski** [klima7/OS#7]
Dobrą praktyką jest ustawienie zegara na jedną częstotliwość i podporządkowanie reszty systemu właśnie jej, np. 1 kHz.

https://github.com/klima7/OS/blob/3d9a0e3fd06d52a455d1e735df7f1482b2e26bbb/clock.c#L21

**Comment by klima7** [comment]
Funkcja set_frequency zmieniona na static
